### ISSUE TITLE
Determine what fields are needed in properties in result schema

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#1]

**Comment by JesseCrocker** [comment]
It should probably contain a field for what level of government manages the land: federal, state, tribal, local, other

**Comment by kdough03** [comment]
- ID
- Name
- Feature type (for a dataset representing a single type of feature, such as national monuments or state forests - determined & entered by person submitting PR. I think this would need to be optional, since the most specific feature type may be in a column in the data itself.) 
- Feature type field (field in dataset that gives the feature type - i.e., column in an FWS dataset that distinguishes refuges and fish hatcheries.)
- Administrative entity (need multiple - i.e., admin1, admin2, admin3?)
- Level of government (federal, state, tribal, local, county, other)
- Data attribution (will this be different from admin entity?)
- FilenameInZip (optional & probably not necessary, but there may be cases where a state bundles multiple public lands together in separate shp files in the same zip)
- “Filter by” (feature type or admin entity - optional)
- URL (link to park/feature website?)
