### ISSUE TITLE
Consider using CPAD for California protected lands

### ISSUE THREAD

**Issue by danrademacher** [OpenBounds/PublicLands#40]
As I mentioned in my SOTMUS talk, we at GreenInfo aggregate all protected lands in California, updated 2X per year and drawing from about 1000 agencies. 

There's a download link here: http://www.calands.org. That'll get you multiple shapefiles. Best one for rec. use is `CPAD_2016a_SuperUnits` (others split parks by county or into holdings, used by acquisition managers vs. regular park users). 

To get accessible parks, filter for `access_typ = "Open Access"`, and that should get you about 12,600 parks. Not sure if you want to chop out small parks for your uses, but this is the best data on California by far.

**Comment by talllguy** [comment]
This is a pretty rad project! I missed the talk, so forgive me. Is the reason for doing this because CA gov agencies aren't already doing a good job at collecting and publishing this data? I'm curious because I sit on an open data council in Maryland and would be interested in seeing some privatization of some of these datasets in my state.

**Comment by JesseCrocker** [comment]
@danrademacher Thanks for the data!
