### ISSUE TITLE
Find some data sources to use to determine what changes we need to make to processing code for this project

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#8]
Find a couple data sources, no need to submit pull requests yet. Put links, a list of fields, a few sample rows, and any comments on here.

**Comment by kdough03** [comment]
Most of the data sources look pretty straightforward - similar to this [WV state forest data](http://catalog.data.gov/dataset/west-virginia-state-forest-boundaries).

![va-state-forests-sample](https://cloud.githubusercontent.com/assets/15642783/14215239/bd2f7f04-f80f-11e5-99d5-555edb1a2e87.png

However, there are some potential issues to be ironed out with some federal-level data:
Areas administered by more than 1 agency - for example, an indian reservation located in a national forest. The [BIA data](http://catalog.data.gov/dataset/tiger-line-shapefile-2014-series-information-file-for-the-current-american-indian-ala) has "admin1" and "admin2" fields. In some cases they're not the primary admin. Would we filter the data so that layer has only primary areas? See screenshot:

![bia](https://cloud.githubusercontent.com/assets/15642783/14215271/005385fa-f810-11e5-8132-79f2e8d91227.png)

(I've used this data since the more recent 2015 data includes off-reservation trust areas, which include 3/4 of the state of OK.)

The [Federal Lands of the US](http://catalog.data.gov/dataset/federal-lands-of-the-united-states-direct-download) dataset also illustrates this problem:

![fed-lands-of-us](https://cloud.githubusercontent.com/assets/15642783/14215517/7a7eeeae-f811-11e5-81c5-93b33670342a.png)

Feature 1 is for the primary or only type of Federal land and the owning agency.  Where an area represents multiple Federal land types, this attribute describes the smaller or 'contained' land.

Feature 2: The secondary type of Federal land and the owning agency.  Where an
        area represents multiple Federal land types, this attribute, in
        general, describes land that surrounds or 'contains' the land
        referenced in Feature1.  Feature2 may also be coded as 'Open Water' if a
        part of the Federal property referenced in Feature1 includes water.

Feature 3: The tertiary type of Federal land and the owning agency.  Where an
        area represents multiple Federal land types, this attribute, in
        general, describes land that surrounds or 'contains' the land
        referenced in Feature2.  Feature3 may also be coded as 'Open Water' if a
        part of the Federal property referenced in Feature2 includes water.

The data also includes 3 name fields corresponding to the 3 feature fields.

There's a higher-resolution version of this data, but the fields are less detailed. The data also may not show inholdings. Only referring to this dataset because it illustrates some of the issues we'll run into. Also, maybe use some of the higher-resolution data where better data isn't available from the individual agencies? 

BLM has statewide land ownership data down to the local level through the BLM GIS portal for each individual state. It also includes more than 1 admin agency:

![co-statewide-land-ownership](https://cloud.githubusercontent.com/assets/15642783/14217432/fb99836e-f81b-11e5-8701-93edc6a6d07d.png)

![co-statewide-land-ownership-map-view](https://cloud.githubusercontent.com/assets/15642783/14217538/a331a836-f81c-11e5-8365-c877b04c047a.png)

The [FWS data](http://catalog.data.gov/dataset/fws-interest-simplified6486d) includes complex name and unit name, but I think the complex may be the only extra field we may possibly want. Also, areas administered as part of the National Wildlife Refuge System and managed by the state under cooperative agreements between the Service and a state fish and wildlife agency. These features are listed as COORD in the RSL_TYPE (organization type) field.

![fws](https://cloud.githubusercontent.com/assets/15642783/14216106/f1b80f84-f814-11e5-960e-19367e1584eb.png)

I'll add the list of fields to PR #1.
